# Generated by Django 4.2.13 on 2026-06-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upwork_id', models.CharField(max_length=120, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=500)),
                ('job_upwork_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VIEWED', 'Viewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interviewing'), ('WON', 'Won'), ('DECLINED', 'Declined'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=15)),
                ('cover_letter', models.TextField(blank=True)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
