# Generated by Django 4.2.13 on 2026-06-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upwork_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('contract_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('FIXED', 'Fixed Price')], default='FIXED', max_length=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upwork_id', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('RELEASED', 'Released'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.contract')),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['due_date'],
            },
        ),
    ]
