# Generated by Django 4.2.13 on 2026-06-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upwork_id', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('job_success_score', models.FloatField(blank=True, null=True)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_jobs', models.IntegerField(default=0)),
                ('connects_balance', models.IntegerField(default=0)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freelancer_profiles',
            },
        ),
    ]
